name: nlp  # Name of the conda environment
channels:
  - defaults
  - nvidia
  - pytorch-nightly
  - conda-forge
dependencies:
  - pytorch 
  - torchvision 
  - torchaudio 
  - pytorch-cuda=12.1 
  - ipykernel
  - ipywidgets
  - pandas 
  - transformers==4.31.0
  - accelerate==0.21.0
  - einops==0.6.1
  - evaluate==0.4.0
  - scikit-learn==1.2.2
  - sentencepiece==0.1.99
  - wandb==0.15.3
  - pip:
    - bitsandbytes==0.40.0
    - peft==0.4.0